@TaskManager.Api_HostAddress = http://localhost:5152

### Create a new user
POST {{TaskManager.Api_HostAddress}}/api/users/create
Content-Type: application/json
Accept: application/json

{
  "FirstName": "Тестовый2",
  "LastName": "Пользователь",
  "Email": "test.user@example.com",
  "Password": "securepassword123",
  "Status": 2,
  "phone": "+1234567890"
}
###